services:
  nginx-service:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gametube-backend-1
      - gametube-backend-2
      - gametube-backend-3
      - gametube-backend-4
  gametube-frontend:
    image: gametube-frontend:03
    ports:
      - "5173:5173"
    depends_on:
      - nginx-service
    environment:
      - VITE_SERVER=http://localhost:4000
  gametube-backend-1:
    image: gametube-backend:03
    ports:
      - "3000:3000"
    env_file:
      - server/.env
  gametube-backend-2:
    image: gametube-backend:03
    ports:
      - "3001:3000"
    env_file:
      - server/.env
  gametube-backend-3:
    image: gametube-backend:03
    ports:
      - "3002:3000"
    env_file:
      - server/.env
  gametube-backend-4:
    image: gametube-backend:03
    ports:
      - "3003:3000"
    env_file:
      - server/.env
    
