services:
  gametube-frontend:
    image: gametube-frontend:01
    ports:
      - "5173:5173"
    environment:
      - VITE_SERVER=http://localhost:4000
  gametube-backend:
    image: gametube-backend:01
    ports:
      - "3000:3000"
    env_file:
      - server/.env
