apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gametube
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: gametube
      labels:
        app: backend
    spec:
      containers:
      - name: gametube-backend
        image: whitesnek/gametube-backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: DB_HOST
          value: "postgres"  
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "gametube"
        - name: DB_SSLMODE
          value: "disable"
        - name: REDIS_URI
          value: "redis:6379"

