apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gametube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      namespace: gametube
      labels:
        app: frontend
    spec:
      containers:
      - name: gametube-frontend
        image: whitesnek/gametube-frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: VITE_SERVER
          value: http://backend:3000

