apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: gametube
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres-pod
      namespace: gametube
      labels:
        app: postgres
    spec:
      containers:
      - name: gametube-postgres
        image: postgres:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "gametube"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
