apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: gametube
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis-pod
      namespace: gametube
      labels:
        app: redis
    spec:
      containers:
      - name: gametube-redis
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
